name: Test Coverage

on:
  pull_request:
    branches:
      - master

jobs:
  test-app:
    name: Test Coverage Report
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Check prettier
        run: yarn run prettier:check

      - name: Generate test coverage report
        id: test_coverage
        run: |
          RESULT=$(npm run test:coverage | tail -n 1)
          echo "::set-output name=coverage_results::$RESULT"

      - name: Post test coverage report
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: ${{ steps.test_coverage.outputs.coverage_results }}
          token: ${{ secrets.MEROXA_MACHINE }}
