name: Release

on:
  push:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.check.outputs.version}}
      changed: ${{ steps.check.outputs.changed}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.MEROXA_MACHINE }}
          fetch-depth: 0

      - name: Check version change
        uses: EndBug/version-check@v2
        id: check

  release:
    runs-on: ubuntu-latest
    needs: check
    if: needs.check.outputs.changed == 'true'
    env:
      TAG: ${{ format('v{0}', needs.check.outputs.version) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.MEROXA_MACHINE }}
          fetch-depth: 0

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: |
          yarn run build:prod

      - name: Push tag
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git tag -a $TAG -m "release: $TAG"
          git push origin $TAG

      - name: NPM publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public

      - name: Github release
        run: |
         yarn add @octokit/action
         node .github/actions/github-release.js
        env:
          GITHUB_TOKEN: ${{ secrets.MEROXA_MACHINE }}
