name: Tests

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test-app:
    name: Running Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.MEROXA_MACHINE_USER_PAT }}

      - name: Use Node
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Configure Git
        run: git config --global --add url."git@github.com:".insteadOf "https://github.com/"

      - name: Configure SSH
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.MEROXA_MACHINE_USER_SSH_KEY }}

      - name: Install dependencies
        run: yarn install

      - name: Running tests
        run: yarn run test

      - name: Generate test coverage report
        id: test_coverage
        run: |
          RESULT=$(yarn run test:coverage-report:ci | tail -n 2)
          echo "::set-output name=coverage_results::$RESULT"

      - name: Post test coverage report
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: ${{ steps.test_coverage.outputs.coverage_results }}
